[package]
name = "voxelinator"
version = "0.1.0"
edition = "2024"
default-run = "voxelinator"

[dependencies]
image = "0.25.6"
indicatif = "0.17.11"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
struct-builder = "0.3.0"
structopt = "0.3.26"
